language: haskell
ghc:
  - 7.6.3
  - 7.8.4
  - 7.10.3
  - 8.0
  - 8.2
env:
  - PACKAGEDIR="source"
  - PACKAGEDIR="testing"
script:
    - cabal install
    - cabal configure --enable-tests && cabal build && cabal test
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install jlex cup openjdk-6-jdk
  - sudo apt-get install g++
  - sudo apt-get install texlive-latex-base
  - sudo apt-get install alex happy
  - export CLASSPATH=".:/usr/share/java/JLex.jar:/usr/share/java/cup.jar"
  - cd ${PACKAGEDIR}
